security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - App\Security\ApiTokenAuthenticator

                # redirect anonymous users to the login page
                entry_point: App\Security\LoginFormAuthenticator

            logout:
                path: lift_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds

            switch_user: true

    access_control:
        # /login must be accessible by all users at the site
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # /register must be accessible by all users at the site
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # /make-users-just-this-once accessable by anonymous
        - { path: ^/make-users-just-this-once, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Require ADMIN clearance for all pages under /admin
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Require users who want to change their profile or password to log in this session
        - { path: ^/account, roles: IS_AUTHENTICATED_FULLY }
        # Require all users to have been logged on with a specific timeframe
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
        # - { path: ^/profile, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_TRAINER, ROLE_MEMBER, ROLE_ALLOWED_TO_SWITCH]
